- action:
  - data:
      entity_id: switch.computer_lamp
    service: switch.turn_on
  alias: Lamp ON with lights
  condition: []
  id: '1504878131921'
  trigger:
  - entity_id: light.dining_area
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: switch.computer_lamp
    service: switch.turn_on
  alias: Sunset
  condition: []
  id: '1504980770376'
  trigger:
  - entity_id: sun.sun
    from: above_horizon
    platform: state
    to: below_horizon
- action:
  - data:
      event: Connor
    service: ifttt.trigger
  alias: Connor Home
  condition:
  - condition: state
    entity_id: device_tracker.stuart
    state: not_home
  id: '1505140044247'
  trigger:
  - entity_id: device_tracker.connor
    from: not_home
    platform: state
    to: home
- action:
  - data:
      event: Kelly
    service: ifttt.trigger
  alias: Kelly Home
  condition:
  - condition: state
    entity_id: device_tracker.stuart
    state: not_home
  id: '1505140537434'
  trigger:
  - entity_id: device_tracker.kelly
    from: not_home
    platform: state
    to: home
- action:
  - data:
      event: You
    service: ifttt.trigger
  alias: Me home
  condition: []
  id: '1505140634968'
  trigger:
  - entity_id: device_tracker.stuart
    from: not_home
    platform: state
    to: home
- action:
  - data:
      entity_id: switch.porch_light
    service: switch.turn_on
  alias: Porch on at sunset
  condition: []
  id: '1505146025825'
  trigger:
  - event: sunset
    platform: sun
- action:
  - data:
      event: KellyLeave
    service: ifttt.trigger
  alias: Kelly Left
  condition:
  - condition: state
    entity_id: device_tracker.stuart
    state: not_home
  id: '1505248774041'
  trigger:
  - entity_id: device_tracker.kelly
    from: home
    platform: state
    to: not_home
- action:
  - data:
      event: ConnorLeave
    service: ifttt.trigger
  alias: Connor Leave House
  condition:
  - condition: state
    entity_id: device_tracker.stuart
    state: not_home
  id: '1505248854286'
  trigger:
  - entity_id: device_tracker.connor
    from: home
    platform: state
    to: not_home
- alias: porch light on
  hide_entity: true
  trigger:
  - platform: state
    entity_id: input_boolean.porch_light
    to: 'on'
  action:
  - service: ifttt.trigger
    data:
      event: porch_on
      value1: 'on'
- alias: porch light off
  hide_entity: true
  trigger:
  - platform: state
    entity_id: input_boolean.porch_light
    to: 'off'
  action:
  - service: ifttt.trigger
    data:
      event: porch_off
      value1: 'off'
- alias: hallway light on
  hide_entity: true
  trigger:
  - platform: state
    entity_id: input_boolean.hallway_light
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.bedtime_timer
- alias: Set theme at startup
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: green
- action:
  - data:
      entity_id: automation.dim_lights_with_kodi
    service: automation.turn_off
  - data:
      entity_id: media_player.kodi_media_center
      message: hello. and welcome to the ramsay's ultimate entertainment center. Alexa
        is on standby to be your kodi assistant. All you need to do is ask. Have a
        pleasant viewing experience
    service: tts.google_say
  - data:
      entity_id: automation.dim_lights_with_kodi
    service: automation.turn_on
  alias: Kodi Welcome Message
  condition: []
  id: '1505828935729'
  trigger:
  - entity_id: media_player.kodi_media_center
    from: 'off'
    platform: state
    to: idle
- action:
  - data:
      entity_id: scene.media_paused
    service: scene.turn_on
  alias: Restore lights with Kodi Pause
  condition: []
  id: '1505831882950'
  trigger:
  - entity_id: media_player.kodi_media_center
    platform: state
    to: paused
- action:
  - data:
      entity_id: scene.media_playing
    service: scene.turn_on
  alias: Dim lights with Kodi
  condition: []
  id: '1505832922571'
  trigger:
  - entity_id: media_player.kodi_media_center
    platform: state
    to: playing
- action:
  - data:
      entity_id: scene.media_stopped
    service: scene.turn_on
  alias: Restore Lights when Kodi stopped
  condition: []
  id: '1505832988462'
  trigger:
  - entity_id: media_player.kodi_media_center
    from: playing
    platform: state
    to: idle
- action:
  - data:
      brightness: '178'
      color_temp: '313'
      entity_id: light.dining_area
      rgb_color:
      - 59
      - 76
      - 255
      transition: '5'
    service: light.turn_on
  alias: _development
  condition: []
  id: '1505836211907'
  trigger:
  - entity_id: switch.computer_lamp
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: bedtime_timer
    service: homeassistant.turn_on
  alias: _Bedtime Test
  condition: []
  id: '1506113773496'
  trigger:
  - entity_id: input_boolean.bedtime
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: switch.oil_burner
    service: switch.turn_on
  alias: Oil Burner ON with Lights
  condition:
  - condition: sun
    after: sunset
    after_offset: -01:30:00
  id: '1506267043199'
  trigger:
  - entity_id: light.lounge_area
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: switch.oil_burner
    service: switch.turn_on
  alias: Oil Burner ON with Lights 2
  condition:
  - condition: state
    entity_id: light.lounge_area
    state: 'on'
  id: '1506338078968'
  trigger:
  - event: sunset
    offset: -01:30:00
    platform: sun
- action:
  - data:
      entity_id: switch.oil_burner
    service: switch.turn_off
  alias: Oil Burner OFF with lights
  condition: []
  id: '1506338228679'
  trigger:
  - entity_id: light.lounge_area
    from: 'on'
    platform: state
    to: 'off'
- action:
  - data:
      entity_id: switch.computer_lamp
    service: switch.turn_off
  alias: Lamp OFF with lights
  condition: []
  id: '1506338533847'
  trigger:
  - entity_id: light.dining_area
    from: 'on'
    platform: state
    to: 'off'
- action:
  - data:
      entity_id: switch.leo
    service: switch.turn_off
  alias: Leo OFF
  condition: []
  id: '1506444905954'
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
- action:
  - data:
      entity_id: switch.leo
    service: switch.turn_on
  alias: Leo ON
  condition: []
  id: '1506444950210'
  trigger:
  - event: sunrise
    offset: +00:30:00
    platform: sun
- action:
  - data:
      entity_id: switch.fireplace
    service: switch.turn_on
  alias: Fireplace light on
  condition: []
  id: '1506445060063'
  trigger:
  - entity_id: light.lounge_area
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: switch.fireplace
    service: switch.turn_off
  alias: Fireplace Light off
  condition: []
  id: '1506502582416'
  trigger:
  - entity_id: light.lounge_area
    from: 'on'
    platform: state
    to: 'off'
- action:
  - data:
      message: Oil Burner has been left on while no one is in the house. http://ramsay.duckdns.org:8123
        <- Click here to open home assistant front end to switch off.
      title: WARNING!
    service: notify.email
  alias: Oil Burner left on
  condition:
  - condition: state
    entity_id: switch.oil_burner
    state: 'on'
  id: '1506516919815'
  trigger:
  - entity_id: group.all_devices
    platform: state
    to: not_home
- action:
  - data:
      message: Home assistant has been shutdown.
      title: HA SHUTDOWN!
    service: notify.pushbullet
  alias: Shutdown Notification
  condition: []
  id: '1506517464543'
  trigger:
  - event: shutdown
    platform: homeassistant
- action:
  - alias: ''
    data:
      entity_id: switch.leo
    service: switch.turn_on
  alias: Leo State Set Correction
  condition:
  - before: sunset
    before_offset: -00:30:00
    condition: sun
  id: '1506525522181'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data:
      message: Home Assistant has successfully been started.
      title: Home Assistant Started
    service: notify.pushbullet
  alias: Bootup Notification
  condition: []
  id: '1506936791021'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data:
      entity_id: script.arrive_home_stu
    service: script.turn_on
  alias: Arrive Home (Stuart)
  condition:
  - condition: state
    entity_id: device_tracker.group
    state: not_home
  - after: sunset
    after_offset: -01:30:00
    condition: sun
  id: '1506941317295'
  trigger:
  - entity_id: device_tracker.stuart
    from: not_home
    platform: state
    to: home
- action:
  - data:
      message: ''
      title: Home Assistant Update Available
    service: notify.pushbullet
  alias: Update Notifier
  condition: []
  id: '1508762059621'
  trigger:
  - entity_id: updater.updater
    platform: state
- action:
  - data:
      entity_id: scene.bedroom_bright
    service: scene.turn_on
  alias: Bedroom Light to Default Brightness - If switch is on
  condition:
  - condition: state
    entity_id: input_boolean.default_bedroom
    state: 'on'
  id: '1509027251180'
  trigger:
  - entity_id: light.master_bedroom
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: input_boolean.stella_detector
    service: input_boolean.turn_on
  alias: Steve's Here
  condition: []
  id: '1509459291781'
  trigger:
  - entity_id: device_tracker.steve
    from: not_home
    platform: state
    to: home
- action:
  - data:
      entity_id: scene.steves_here
    service: scene.turn_on
  alias: Steve arrive lights
  condition: []
  id: '1509459487635'
  trigger:
  - entity_id: input_boolean.stella_detector
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: input_boolean.ice_detector
    service: input_boolean.turn_on
  alias: Icy Work Morning
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - after: 06:00
    before: 09:00
    condition: time
  id: '1509462614901'
  trigger:
  - below: '3'
    entity_id: sensor.dark_sky_temperature
    platform: numeric_state
- action:
  - data:
      entity_id: input_boolean.default_bedroom
    service: input_boolean.turn_off
  - delay: '3'
  - data:
      entity_id: scene.icy_car
    service: scene.turn_on
  - data:
      entity_id: input_boolean.ice_detector
    service: input_boolean.turn_off
  alias: Icy Windscreen Warning Light
  condition: []
  id: '1509463021729'
  trigger:
  - entity_id: input_boolean.ice_detector
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: input_boolean.default_bedroom
    service: input_boolean.turn_on
  alias: Bedroom Brightness Default Reset
  condition:
  - condition: state
    entity_id: input_boolean.override_patch
    state: 'off'
  id: '1509464422600'
  trigger:
  - entity_id: light.bedroom
    from: 'on'
    platform: state
    to: 'off'
