- platform: yr
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
- platform: rest
  resource: !secret light_sensor_api
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Bathroom Lux'
  
- platform: rest
  resource: !secret temp_sensor_api
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Bathroom Temperature'
  
  
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: disk_free
      arg: /home
    - type: memory_use_percent
    - type: memory_free
    - type: processor_use
    - type: last_boot
    - type: since_last_boot
    
- platform: google_travel_time
  api_key: !secret google_api_key
  origin: !secret google_origin
  destination: !secret google_destination

- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - temperature
    - apparent_temperature
    - wind_speed
    - cloud_cover

- platform: torque
  email: ramsay1984@gmail.com
